# Host to use for canonical URL generation (without trailing slash)
host: registers-tech-docs.cloudapps.digital

# Header-related options
show_govuk_logo: true
service_name: Registers documentation
service_link: https://registers.cloudapps.digital/
phase: Beta

# Links to show on right-hand-side of header
header_links:
  About: https://registers.cloudapps.digital/
  Using Registers: https://registers.cloudapps.digital/using-registers.html
  Documentation: /
  Support: https://registers.cloudapps.digital/support.html

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:
